# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_note_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(max_length=30)),
                ('comment_book', models.CharField(max_length=30)),
                ('comment_title', models.CharField(max_length=30)),
                ('comment_rate', models.CharField(max_length=30)),
                ('comment_content', models.CharField(max_length=300)),
            ],
        ),
    ]
