# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20160728_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
