# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_comment_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=50)),
                ('comment_time', models.CharField(max_length=50)),
            ],
        ),
    ]
