# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20160728_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score_star',
            field=models.CharField(default='', max_length=100),
        ),
    ]
