# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='comment_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
