# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20160728_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
