# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_comment_comment_time'),
        ('books', '0012_auto_20160728_1446'),
    ]

    operations = [
    ]
