# Generated by Django 2.0 on 2017-12-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160730_1956'),
        ('books', '0013_merge'),
    ]

    operations = [
    ]
